project:
  type: book
  output-dir: docs

book:
  title: "ISLR-R21._1"
  author: "Mücahit Zor"
  search: true
  downloads: [pdf,epub]
  sharing: twitter
  date: "8/23/2023"
  chapters:
    - index.qmd
    - Chapter2.qmd
    - Chapter3.qmd

bibliography: references.bib


format:
  html:
    theme: minty
    mainfont: Circular
  pdf:
    documentclass: scrreprt

editor: visual

