project:
  type: book
  output-dir: docs

book:
  title: "ISLR-R21._1"
  author: "Mücahit Zor"
  search: true
  downloads: [pdf,epub]
  sharing: twitter
  date: "8/23/2023"
  chapters:
    - index.qmd
    - Chapter2.qmd
    - Chapter3.qmd
    - ExerciseLinearModel.qmd

bibliography: references.bib

sidebar:
  pinned: true
  align: center
  

highlight-style: a11y
format:
  html:
    page-layout: full
    theme: 
      light: minty
      dark: darkly
    code-overflow: wrap
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

